name: CI/CD Pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_app:
    name: Build Sample App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Building app
        run: bazel build //:all

  deploy_app:
    name: Deploy Sample App to EC2
    needs:
      - build_app
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Building app
        run: bazel build //:all
      - name: Deploy App
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: ${{ env.GITHUB_WORKSPACE }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_DIRECTORY }}
          EXCLUDE: "/bazel-out/, /bazel-testlogs/, /.git/"
